"""backend_fastapi/routers/export.py - 結果エクスポート & PDFレポート生成"""
from fastapi import APIRouter, HTTPException, Response
from pydantic import BaseModel, Field
from typing import Dict, Any, Optional
import logging, json, io

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/export", tags=["export"])

class ExportPayload(BaseModel):
    format: str = Field(..., pattern="^(csv|json|pdf)$")
    result: Dict[str, Any]
    metadata: Dict[str, Any] = Field(default_factory=dict)

@router.post("/generate")
async def export_report(payload: ExportPayload):
    try:
        if payload.format == "json":
            content = json.dumps({
                "result": payload.result,
                "metadata": payload.metadata
            }, ensure_ascii=False, indent=2)
            return Response(
                content=content, 
                media_type="application/json", 
                headers={"Content-Disposition": "attachment; filename=analysis_result.json"}
            )
            
        elif payload.format == "pdf":
            # WeasyPrint によるHTML→PDF変換
            try:
                from weasyprint import HTML
            except ImportError:
                logger.error("WeasyPrint not installed")
                raise HTTPException(503, "WeasyPrint がサーバーにインストールされていないため、PDF出力は利用できません。")
            
            res = payload.result
            meta = payload.metadata
            metrics = res.get('metrics', {})
            importances = res.get('feature_importance', [])
            
            html_content = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {{ font-family: sans-serif; color: #1e293b; padding: 40px; }}
                    h1 {{ color: #0f172a; border-bottom: 2px solid #06b6d4; padding-bottom: 10px; }}
                    .summary {{ background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0; }}
                    .metric-box {{ display: inline-block; width: 45%; margin-bottom: 20px; }}
                    .label {{ font-size: 12px; color: #64748b; text-transform: uppercase; }}
                    .value {{ font-size: 20px; font-weight: bold; color: #0ea5e9; }}
                    table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
                    th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }}
                    th {{ background: #f1f5f9; color: #475569; font-size: 12px; }}
                </style>
            </head>
            <body>
                <h1>ChemAI Nexus Analysis Report</h1>
                <p>Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC</p>
                
                <div class="summary">
                    <h3>Analysis Summary</h3>
                    <div class="metric-box">
                        <div class="label">Filename</div>
                        <div class="value">{meta.get('filename', 'N/A')}</div>
                    </div>
                    <div class="metric-box">
                        <div class="label">Best Model</div>
                        <div class="value">{res.get('best_model', 'Unknown')}</div>
                    </div>
                    <div class="metric-box">
                        <div class="label">R² Score</div>
                        <div class="value">{metrics.get('r2', 0.0):.4f}</div>
                    </div>
                    <div class="metric-box">
                        <div class="label">RMSE</div>
                        <div class="value">{metrics.get('rmse', 0.0):.4f}</div>
                    </div>
                </div>

                <h3>Feature Importance (Top 15)</h3>
                <table>
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Feature Name</th>
                            <th>Importance Score</th>
                        </tr>
                    </thead>
                    <tbody>
                        {''.join(f'<tr><td>{i+1}</td><td>{f["feature"]}</td><td>{f["importance"]:.4f}</td></tr>' for i, f in enumerate(importances[:15]))}
                    </tbody>
                </table>
                
                <p style="margin-top: 40px; font-size: 10px; color: #94a3b8; text-align: center;">
                    Generated by ChemAI Nexus - Modern ML stack for Chemoinformatics
                </p>
            </body>
            </html>
            """
            pdf_bytes = HTML(string=html_content).write_pdf()
            return Response(
                content=pdf_bytes, 
                media_type="application/pdf", 
                headers={"Content-Disposition": "attachment; filename=chemai_report.pdf"}
            )
            
        raise HTTPException(400, f"Unsupported format: {payload.format}")
    except Exception as e:
        logger.error(f"Export failed: {e}", exc_info=True)
        raise HTTPException(500, str(e))

from datetime import datetime
