# backend/llm/eda_plotter.py
"""
Natural language EDA plot generation via LLM.

User can describe the plot they want in natural language,
and LLM generates the corresponding plot configuration/code.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
import logging
import json

from backend.llm.provider import LLMProvider, LLMRequest
from backend.llm import get_llm_provider

logger = logging.getLogger(__name__)


@dataclass
class PlotSpec:
    """Specification for a plot generated by LLM."""
    plot_type: str  # scatter, line, bar, heatmap, pairplot, etc.
    x: str = ""
    y: str = ""
    color: str = ""  # color by this column
    facet_col: str = ""
    facet_row: str = ""
    filters: List[Dict[str, any]] = field(default_factory=list)  # [{column, condition, value}]
    title: str = ""
    x_label: str = ""
    y_label: str = ""
    code: str = ""  # generated code (if any)


class LLMEDAPlotter:
    """
    LLM-powered EDA plot generator from natural language.
    """

    def __init__(self, provider: Optional[LLMProvider] = None):
        self.provider = provider or get_llm_provider("stub")
        if self.provider is None:
            from backend.llm.provider import StubLLMProvider
            self.provider = StubLLMProvider()

    def generate_plot_spec(
        self,
        user_description: str,
        available_columns: List[str],
        column_types: Dict[str, str],
        target_col: str = "",
        sample_data: str = "",  # first few rows as string
    ) -> PlotSpec:
        """
        Generate plot specification from natural language description.

        Args:
            user_description: Natural language description (e.g., "plot yield vs temperature, color by solvent")
            available_columns: List of available column names
            column_types: Dict mapping column name to type (numeric, categorical, etc.)
            target_col: Target column name
            sample_data: Optional string representation of first few rows

        Returns:
            PlotSpec with plot configuration
        """
        system_prompt = """あなたはデータ可視化の専門家です。
ユーザーの自然言語によるプロット依頼を解析し、以下のJSON形式で出力してください。

出力形式：
{
  "plot_type": "scatter | line | bar | box | histogram | heatmap | pairplot | correlation",
  "x": "x軸の列名",
  "y": "y軸の列名（ヒストグラム・ボックスプロットでは省略可）",
  "color": "色分けする列名（任意）",
  "facet_col": "列方向のファセット列（任意）",
  "facet_row": "行方向のファセット列（任意）",
  "filters": [
    {"column": "列名", "condition": ">", "value": 100},
    ...
  ],
  "title": "プロットタイトル",
  "x_label": "x軸ラベル（任意）",
  "y_label": "y軸ラベル（任意）"
}

重要：
- plot_type は必ず上記の選択肢から選ぶ
- x, y は必ず利用可能な列名から選ぶ
- 存在しない列名は使わない
- フィルター条件は現実的にする"""

        user_prompt = f"""利用可能な列: {available_columns}
列の型: {column_types}
目的変数: {target_col}

サンプルデータ:
{sample_data}

ユーザーの依頼: {user_description}

上記の依頼に基づいてプロット設定をJSONで出力してください。"""

        request = LLMRequest(
            user_prompt=user_prompt,
            system_prompt=system_prompt,
            max_tokens=1024,
            temperature=0.1,
        )

        try:
            response = self.provider.generate(request)
            return self._parse_plot_spec(response.content, available_columns)
        except Exception as e:
            logger.error(f"LLM plot generation failed: {e}")
            return PlotSpec(plot_type="scatter", x=target_col, y=available_columns[0] if available_columns else "")

    def generate_plot_code(
        self,
        plot_spec: PlotSpec,
        output_format: str = "plotly",  # "plotly" or "matplotlib"
    ) -> str:
        """
        Generate executable Python code for the plot.

        Args:
            plot_spec: PlotSpec from generate_plot_spec()
            output_format: "plotly" or "matplotlib"

        Returns:
            Python code string that can be executed
        """
        system_prompt = f"""あなたはPythonデータ可視化の専門家です。
以下のプロット設定に基づいて、実行可能なPythonコードを生成してください。

要件：
- 使用ライブラリ: {"plotly": "plotly.express", "matplotlib": "matplotlib.pyplot"}[output_format]
- データフレーム名は `df` としてください
- コードのみ出力し、説明は不要
- インポート文も含める
- 最後に fig.show() または plt.show() を含める"""

        user_prompt = f"""プロット設定:
{self._format_plot_spec(plot_spec)}

出力形式: {output_format}

上記設定のプロットコードを生成してください。"""

        request = LLMRequest(
            user_prompt=user_prompt,
            system_prompt=system_prompt,
            max_tokens=2048,
            temperature=0.1,
        )

        try:
            response = self.provider.generate(request)
            return response.content
        except Exception as e:
            logger.error(f"LLM code generation failed: {e}")
            return self._fallback_code(plot_spec, output_format)

    def _parse_plot_spec(
        self, text: str, available_columns: List[str]
    ) -> PlotSpec:
        """Parse LLM response into PlotSpec."""
        try:
            # Find JSON block
            start = text.find("{")
            end = text.rfind("}") + 1
            if start >= 0 and end > start:
                json_str = text[start:end]
                data = json.loads(json_str)
            else:
                raise ValueError("No JSON found")

            return PlotSpec(
                plot_type=data.get("plot_type", "scatter"),
                x=data.get("x", ""),
                y=data.get("y", ""),
                color=data.get("color", ""),
                facet_col=data.get("facet_col", ""),
                facet_row=data.get("facet_row", ""),
                filters=data.get("filters", []),
                title=data.get("title", ""),
                x_label=data.get("x_label", ""),
                y_label=data.get("y_label", ""),
            )

        except Exception as e:
            logger.warning(f"Failed to parse plot spec: {e}")
            return PlotSpec(plot_type="scatter")

    def _format_plot_spec(self, spec: PlotSpec) -> str:
        """Format PlotSpec as string."""
        lines = [
            f"Type: {spec.plot_type}",
            f"X: {spec.x}" if spec.x else "",
            f"Y: {spec.y}" if spec.y else "",
            f"Color: {spec.color}" if spec.color else "",
            f"Facet col: {spec.facet_col}" if spec.facet_col else "",
            f"Facet row: {spec.facet_row}" if spec.facet_row else "",
            f"Title: {spec.title}" if spec.title else "",
        ]
        if spec.filters:
            lines.append("Filters:")
            for f in spec.filters:
                lines.append(f"  - {f}")
        return "\n".join([l for l in lines if l])

    def _fallback_code(self, spec: PlotSpec, output_format: str) -> str:
        """Generate fallback plot code."""
        if output_format == "plotly":
            import_str = "import plotly.express as px"
            if spec.plot_type == "scatter":
                return f"""{import_str}
fig = px.scatter(df, x='{spec.x}', y='{spec.y}',
              color='{spec.color}' if '{spec.color}' else None)
fig.show()"""
            else:
                return f"""{import_str}
fig = px.scatter(df, x='{spec.x}', y='{spec.y}')
fig.show()"""
        else:
            return f"""import matplotlib.pyplot as plt
plt.scatter(df['{spec.x}'], df['{spec.y}'])
plt.xlabel('{spec.x}')
plt.ylabel('{spec.y}')
plt.show()"""


def apply_filters(df, filters: List[Dict]) -> "DataFrame":
    """Apply filters to dataframe."""
    import pandas as pd
    query_parts = []
    for f in filters:
        col = f.get("column", "")
        cond = f.get("condition", "==")
        val = f.get("value", "")
        if col and cond and val != "":
            query_parts.append(f"`{col}` {cond} {val}")
    if query_parts:
        return df.query(" & ".join(query_parts))
    return df


if __name__ == "__main__":
    # Simple test
    plotter = LLMEDAPlotter()
    spec = plotter.generate_plot_spec(
        user_description="温度と収率の関係をプロットして、溶媒で色分けしたい",
        available_columns=["temp", "yield", "solvent", "pressure"],
        column_types={"temp": "numeric", "yield": "numeric", "solvent": "categorical", "pressure": "numeric"},
        target_col="yield",
        sample_data="temp,yield,solvent\n100,0.8,Water\n150,0.9,Ethanol",
    )
    print(f"Plot type: {spec.plot_type}")
    print(f"X: {spec.x}, Y: {spec.y}, Color: {spec.color}")

    code = plotter.generate_plot_code(spec, output_format="plotly")
    print(f"\nGenerated code:\n{code}")
